### ISSUE TITLE
Android: Border radius problem 

### ISSUE THREAD

**Issue by egemenokten** [WrathChaos/react-native-tab-bars#1]
Active tab radius seems not working correctly 

<p align="center">
<img alt="Activity Feed Tab" src="https://user-images.githubusercontent.com/30256104/69579238-27538800-0fe3-11ea-986c-63ed21d0f112.png" width="49.7%" />
<img alt="Gallery Tab" src="https://user-images.githubusercontent.com/30256104/69579251-2de1ff80-0fe3-11ea-91a0-f59c86747517.png" width="49.7%"/>
</p>

**Comment by WrathChaos** [comment]
#2 Fixed this issue.

Check it out this new release: 

## [Release 0.0.5  🎊🎉](https://github.com/WrathChaos/react-native-tab-bars/releases/tag/0.0.5)
